### PR TITLE
Restructuring files and adding __init__.py file

### PR DESCRIPTION
**Pull request by amirHosseinAsghari**
When I tried running the code it wasn't possible becuase it was returning ModuleNotFoundError
So I created lib folder in order to seperate custom modules from the main.py file and add __init__.py file to declare the folder as a python package
Hope you like it

### CODE REVIEW

**Comment by rly0nheart** [comment]
Oh damn, I just realised I removed the init file from the last push. Now this can be solved by adding the __init__.py file. I will look at your changes right away

**Comment by amirHosseinAsghari** [comment]
> @amirHosseinAsghari oh damn, I must have removed the init file from the last push. Now this can be solved by adding the **init**.py file. Though I will look at your changes right away.
> 
> Edit: These look good, let me just run some tests, I'll let you know how it goes.
> 
> Also, how did you run it to get the ModuleNotFoundError?


Screenshot from 2023-04-29 13-29-55
This is a screenshot of the error I got earlier

**Comment by rly0nheart** [comment]
> > @amirHosseinAsghari oh damn, I must have removed the init file from the last push. Now this can be solved by adding the **init**.py file. Though I will look at your changes right away.
> > 
> > Edit: These look good, let me just run some tests, I'll let you know how it goes.
> > 
> > Also, how did you run it to get the ModuleNotFoundError?
> 
> 
> Screenshot from 2023-04-29 13-29-55
> This is a screenshot of the error I got earlier

I see, but that's not how you're supposed to run it. The code structure is that of a python package, that's an uncompiled package. So I recommend you install it from pypi using pip.
Then let me know how it goes

**Comment by rly0nheart** [comment]
I assume you have it working. I will close this now, thank you for contributing😁

**Pull request closed without merging**
